# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: twright
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: scribe
# "service" is the name of this project. This will also be added to your AWS resource names.
service: scribe
state: s3-state-resolver

stages:
  default:
    resolvers:
      generic:
        type: aws
        s3-state-resolver:
          type: s3
          region: "ap-southeast-2"
          bucketName: nimo-challenge-serverless-deployment

package:
  excludeDevDependencies: true
  individually: true
  exclude:
    - .*/**

provider:
  name: aws
  runtime: nodejs20.x
  region: "ap-southeast-2"
  deploymentBucket:
    name: nimo-challenge-serverless-deployment

functions:
  write_event_log:
    handler: handlers.WriteEvent
    name: scribe_write_event_log
    environment:
      DEBUG_LOGGING: TRUE
      # RDS connection variables
      RDS_HOSTNAME: ${env:RDS_HOSTNAME}
      RDS_PORT: ${env:RDS_PORT}
      RDS_USERNAME: ${env:RDS_USERNAME}
      RDS_PASSWORD: ${env:RDS_PASSWORD}
      # Event log db connection
      EVENT_LOG_DB_NAME: ${env:EVENT_LOG_DB_NAME}